- www/epiviz.html
- www/epiviz_panel_designer.html
referencing this issue, not sure when this changed
https://github.com/IGS/gEAR/issues/23
> fix: update epiviz urls

- www/index.html
- www/js/classes/tree.js
- www/js/index.js
This is a pull request to make gene carts selectable from the front page.
> Gene Carts show on front page

- lib/gear/plotting.py
- www/api/resources/plotly_data.py
- www/css/dataset_curator.css
- www/js/dataset_curator.js
This adds error messages in the event that plotly plots fail in the dataset curator.  Since scanpy (tsne) and SVG API calls return different JSON structures, this does not work for them
> Dataset curator error msgs

- www/js/analyze_dataset.js
- www/js/classes/user.js
- www/js/comment.js
- www/js/common.js
- www/js/compare_datasets.js
- www/js/create_account.js
- www/js/dataset_curator.js
- www/js/dataset_explorer.js
- www/js/epiviz_panel_designer.js
- www/js/gene_cart_manager.js
- www/js/index.js
- www/js/manual.js
- www/js/multigene_curator.js
- www/js/projection.js
- www/js/sidepanel_notes.js
- www/js/upload_dataset.js
- www/js/upload_epigenetic_dataset.js
- www/js/user_profile.js
- www/js/workshop.js
Resolves #341 for the main branch
> Mirroring commit 2377b2f

- www/cgi/get_organism_list.cgi
- www/index.html
- www/js/classes/ui-panel-annotation.js
- www/js/classes/ui-panel-dataset-collection.js
- www/js/common.js
- www/js/index.js
There's still one issue (organism isn't updating on profile change), but merging now to fix the broken links
> Organism selectors

- bin/add_ensembl_id_to_h5ad_missing_release__file_based.py
- bin/add_excel_metadata_to_db.py
- bin/convert_3tab_to_h5ad.py
- bin/profile_single_heatmap_run.py
- bin/scan_datasets_for_ensembl_and_gene_symbols.py
- bin/validate_observation_ids.py
- docs/setup.python.md
- lib/gear/metadata.py
- www/css/workshop.css
- www/js/classes/ui-panel-dataset-collection.js
- www/js/index.js
- www/js/workshop.js
- www/workshop/index.html
Gene search results stay on index.html.
Projection results now belong on projection.html
This makes it easier to develop and debug the two separate codebases
> Split projection code onto its own HTML

- bin/create_annotation_orthology_maps.py
- lib/gear/orthology.py
- lib/geardb.py
- www/api/api.py
- www/api/resources/multigene_dash_data.py
- www/api/resources/orthologs.py
- www/api/resources/plotly_data.py
- www/api/resources/projectr.py
- www/api/resources/svg_data.py
- www/api/resources/tsne_data.py
- www/include/tile-grid/tile.html
- www/js/classes/tilegrid.js
- www/js/common.v2.js
- www/js/expression.js
Orthology mapping works now, though the feature mapping files will need to be built using `bin/create_annotation_orthology_maps.py` again.
> UI v2 orthology refactoring

- www/compare_datasets.html
Bad HTML ID from when I converted snake_case to kebab-case in the id names
> Resolves #678

- lib/gear/plotting.py
- www/api/resources/aggregations.py
- www/js/curator_common.js
- www/js/dataset_curator.js
This pull request includes several changes to improve error handling, enhance functionality, and fix minor bugs in the `plotting.py`, `aggregations.py`, `curator_common.js`, and `dataset_curator.js` files. The most important changes include adding error handling for missing colormap entries, updating data fetching logic, and improving user feedback in the UI.
* [`lib/gear/plotting.py`](diffhunk://#diff-83fdedc4040f046d004d91bf0221a66afe5d43aab81bda6193963cc1b4e30102R552-R556): Added a try-except block to handle `KeyError` when a series is not found in the colormap, printing an error message to `stderr` and skipping the coloring. (`[lib/gear/plotting.pyR552-R556](diffhunk://#diff-83fdedc4040f046d004d91bf0221a66afe5d43aab81bda6193963cc1b4e30102R552-R556)`)
* …
> Resolving #926

- www/cgi/remove_gene_cart.cgi
- www/dataset_explorer.html
- www/gene_list_manager.html
- www/js/common.v2.js
- www/js/dataset_explorer.js
- www/js/gene_list_manager.js
This pull request includes several changes to improve the user interface and functionality of the gene list manger and dataset explorer features. The biggest change is making table rows expandable to show more information and actions for each item.  There are also changes that involve modifying identifiers, enhancing UI components, and updating HTML structures.
* Changed the parameter from `gene_list_id` to `share_id` in `www/cgi/remove_gene_cart.cgi` and `www/js/common.v2.js` to standardize the identifier used for gene lists. [[1]](diffhunk://#diff-d0fd1eaf7efe7b6ba1257964a8a3d4902d94d852e5e84914728a6e19a11ddd79L32-R51) [[2]](diffhunk://#diff-d863b1e660318dbbd135523081cab4b2694a428a58c2702fe90d69171a61bc63L868-R872)
* Improved the dataset explorer interface by updating labels and adding …
> Feature 939

- services/spatial/panel_app.py
This pull request to `services/spatial/panel_app.py` includes changes to improve data processing, visualization, and error handling. The most important changes include sorting data frames by `raw_value`, updating marker size calculation, adding UMAP processing, and improving error handling.
Improvements to data processing and visualization:
* Sorted data frames by `raw_value` in several methods to ensure consistent ordering (`make_expression_scatter`, `add_cluster_traces`, `make_umap_plots`, `make_violin_plot`). [[1]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bR100-R105) [[2]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bL118-R124) [[3]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076 …
> Spatial panel improvements

- services/spatial/panel_app.py
- www/sc_workbench.html
This pull request includes changes to the `services/spatial/panel_app.py` and `www/sc_workbench.html` files to improve data processing and user interface settings. The most important changes include updating the UMAP creation process and modifying the default clustering resolution.
Improvements to data processing:
* [`services/spatial/panel_app.py`](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bR685): Added a step to identify highly variable genes before performing PCA, neighbors, and UMAP calculations in the `add_umap` method.
User interface settings:
* [`www/sc_workbench.html`](diffhunk://#diff-60fde616053b36c10f9af3d662fb3c9dba1a23db67b91f6c5c71b6c1c330faf1L1072-R1073): Changed the default clustering resolution from 1.3 to 0.5 in the explanatory text …
> Seurat adjustment + minor single-cell workbench text fix

- docker/docker-compose.yml.template
- lib/geardb.py
- services/spatial/Dockerfile
- services/spatial/panel_app.py
- services/spatial/requirements.txt
- systemd/spatial-panel.service
- www/api/resources/common.py
- www/api/resources/projectr.py
- www/dataset_explorer.html
- www/js/classes/tilegrid.js
This pull request introduces several changes to enhance spatial data handling and improve the functionality of the spatial panel application. The most significant changes include updates to the `panel_app.py` to support projections, modifications to the `docker-compose.yml.template` to include projections volume, and updates to the `geardb.py` to handle spatial datasets.
* [`services/spatial/panel_app.py`](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bR19-R30): Added support for projections by introducing `projection_id` parameter, creating projection AnnData objects, and updating various methods to handle projections. [[1]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bR19-R30) …
> post-ARO workshop merge (projections and bugs)

- services/spatial/panel_app.py
- www/dataset_explorer.html
This pull request includes changes to both the `services/spatial/panel_app.py` and `www/dataset_explorer.html` files, focusing on improving the functionality and user interface of the spatial transcriptomics panel and dataset explorer.
Improvements to spatial transcriptomics panel:
* [`services/spatial/panel_app.py`](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bL395-R397): Removed outdated comments and updated the y-axis configuration in the `make_violin_plot` method to use the correct parameter name `rangemode`.
Enhancements to dataset explorer:
* [`www/dataset_explorer.html`](diffhunk://#diff-cb06071b896c24ddd620d2eefd48a0e75249b4f81afb166acccd13605ea060e2R174): Added a new filter control option for "Spatial Transcriptomics" to the dataset explorer …
> HOTFIX for bad plotly param

- docs/projectR_scratch_notes.md
- www/api/api.py
- www/api/resources/mg_plotly_data.py
- www/js/plot_display_config.js
(#1000) Refactor multigene_dash_data to mg_plotly_data and update related imports; adjust colorbar position in plot_display_config
> multigene display tweaks

- docker/Dockerfile
- services/spatial/panel_app.py
- www/api/resources/projectr.py
This pull request introduces several updates across multiple files to enhance functionality, improve code maintainability, and ensure consistency. The changes primarily focus on refining spatial plotting logic, improving data aggregation, and updating dependencies and configurations.
* Added `cluster_map` to the `SpatialPlot` and its subclasses to map cluster category codes to cluster names, enabling better handling of cluster data in plots (`services/spatial/panel_app.py`). [[1]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bL100-R105) [[2]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bL331-R325) [[3]](diffhunk://#diff-c26c3b35cd2fdd78f7ddbc517c32986d7c7d1377f24018ddc45d94fa87e0076bL554-R528) …
> Projection hotfix

- www/js/classes/tilegrid.js
- www/js/expression.js
- www/js/projection.js
This pull request introduces several updates to enhance the functionality and maintainability of the `DatasetTile` class and related components in the `tilegrid.js` and `expression.js` files. Key changes include improvements to SVG handling, better tooltip and legend rendering, and code style standardization.
* Introduced a new `svg` property in the `DatasetTile` class to store SVG-related data and added an `updateSVGDisplay` method to manage SVG updates dynamically. (`www/js/classes/tilegrid.js`, [[1]](diffhunk://#diff-93f37295b11d7495132184c28172c430c56b8a703e1e3baeab44fb9d71f3a39cR284-R285) [[2]](diffhunk://#diff-93f37295b11d7495132184c28172c430c56b8a703e1e3baeab44fb9d71f3a39cR1655-R1682)
* Updated the `colorSVG` function to accept a `geneSymbol` parameter and enhanced the tooltip and …
> Resolve #1016 plus extra aesthetical cleanup

- bin/convert_3tab_to_h5ad_lowmem.py
- docker/requirements.txt
- docs/setup.python.md
- lib/geardb.py
- www/api/resources/common.py
- www/api/resources/plotly_data.py
- www/api/resources/projectr.py
- www/js/classes/analysis.js
- www/js/projection.js
- www/p
- www/projection.html
This pull request includes updates across multiple areas, including workflow configuration, dependency management, Python code refactoring, and JavaScript bug fixes. The most important changes focus on improving maintainability, updating dependencies, and addressing potential issues in the code.
* [`.github/workflows/codeql.yml`](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27L16-R16): Updated the branch list for CodeQL scans to include `devel` instead of `main` and `ui-v2`. Also upgraded CodeQL actions from version `v2` to `v3` for `init`, `autobuild`, and `analyze` steps. [[1]](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27L16-R16) [[2]](diffhunk://#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27L7 …
> Various bugfixes

- bin/upload_spatial_dataset.py
- docs/uploading_spatial_dataset.md
- lib/gear/datasetuploader.py
- lib/gear/spatial_handler.py
- services/spatial/Dockerfile
- services/spatial/common.py
- services/spatial/panel_app.py
- services/spatial/panel_app_expanded.py
- www/api/resources/common.py
- www/js/classes/tilegrid.js
This pull request introduces significant updates to the spatial dataset handling system, including renaming and refactoring the `spatialuploader.py` module, adding new handler classes for various spatial data platforms, and updating corresponding references across the codebase. Additionally, it introduces a new expanded endpoint for panel applications and updates the Dockerfile and frontend logic to support these changes.
* Renamed `lib/gear/spatialuploader.py` to `lib/gear/spatial_handler.py` and replaced the `SpatialUploader` class with `SpatialHandler` for better modularity and clarity.
* Added new handler classes (`CoxMxHandler`, `GeoMxHandler`, `VisiumHandler`, `VisiumHDHandler`, `XeniumHandler`, etc.) to support various spatial data platforms, replacing the earlier uploader classes. …
> Spatial view rewrite

- www/js/classes/tilegrid.js
- www/js/dataset_curator.js
- www/js/expression.js
- www/js/projection.js
This pull request introduces several updates to improve the handling of zoomed tile displays, refactor the handling of gene inputs, and enhance the overall performance and reliability of the code. Key changes include the introduction of asynchronous operations for rendering displays, replacing `geneSymbol` with `geneInput` for better clarity, and improving event listener management. 
* Added a `zoomId` property to `TileGrid` to track the currently zoomed tile and preserve its state during interactions. (`www/js/classes/tilegrid.js`, [[1]](diffhunk://#diff-93f37295b11d7495132184c28172c430c56b8a703e1e3baeab44fb9d71f3a39cR23-R24) [[2]](diffhunk://#diff-93f37295b11d7495132184c28172c430c56b8a703e1e3baeab44fb9d71f3a39cR299-R312)
* Updated `DatasetTile` to use `geneInput` instead of `geneSymbol` …
> 1082  and 930

- www/js/curator_common.js
Remove unused plot button elements and fix loading state toggle.
> Refactor createPlot function for loading state
